//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instance
    {
        public int id { get; set; }
        public string instance1 { get; set; }
    }
}
